### ISSUE TITLE
[1.16] Fusion Crafting does not work through the Interface, only Redstone Signal (possibly all UI)

### ISSUE THREAD

**Issue by VoltexRB** [Draconic-Inc/Draconic-Evolution#1614]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432

### Description / steps to reproduce
Pretty Self Explanatory, I dont know what I do but I am not able to click the "Craft" Button inside the Fusion Crafter, but everyone else is. I have a normal setup, and looked into if it had something to do with FTB Claimed chunks but that doesnt seem to be the case. It works, if I just send the craft signal with a simple redsone input, like a button. 

![image](https://user-images.githubusercontent.com/56729597/149679106-d292f1f0-475c-409d-9e41-2d402229193b.png)

I also dont seem to be able to use the interface on any machine (Mob Grinder and Energy Transfuser. I have the modpack added to FTB Ultimate Anniversary if that matters.

Update: 
Its working if I lay down my Tinkers Construct Plate Armor. Looking further into it and then going to edit this again if I have any more information.

Update 2:
I cant press any Draconic Evolution UI, when I have Tinkers Construct Plate Chestplate equipped...? For other people with MY complete Armor Set it works, I also tried crafting a completely new one and it still doesnt work, even with the other Tconstruct Plate Chestplate, but still only for me. Now im running into a dead end

**Comment by brandon3055** [comment]
I honestly have no idea why this is happening to you. 
The only thing that could be causing this would have to be my safety system that ensures there is no possible way a player can interact with one of my tiles if they do not have permission to right-click the block. It seems for some reason something is blocking the right-click event when you and only you try to use the block.

If issues like this are possible then the best course of action I have is to add a config to disable my safety system, 

Its not entirely needed because permission plugins will prevent players from accessing my gui's but even without access to the GUI it would theoretically be possible to use a modified client to send a button packet to a tile bypassing the GUI.
And when pressing the wrong button in my mod can result in a 300 block smoking crater... It seemed like a good idea to have a little extra security.

**Comment by brandon3055** [comment]
I just fixed this a few days ago. Update BrandonsCore and the issue should be resolved.
https://github.com/Draconic-Inc/Draconic-Evolution/issues/1653

**Comment by FoxMcloud5655** [comment]
Closing as it's a duplicate issue of one that's already resolved.
