### ISSUE TITLE
Can't initiate DE infusion crafting while wearing Tinkers Chestplate

### ISSUE THREAD

**Issue by Rohmad96** [Draconic-Inc/Draconic-Evolution#1653]
This is the most bizarre, unexpected glitch I've ever come across.
Isolating this was a nightmare, and I couldn't tell you why this happens, but it does. Please let me know if this is a Tinkers issue instead.

**Base information:**
- Minecraft version: 1.16.5
- Mod version: Draconic-Evolution-1.16.5-3.0.22.444-universal | Tinkers' Construct: TConstruct-1.16.5-3.3.4.335
- Minecraft Forge version: 36.2.33
- Mod Pack: FTB Oceanblock 1.12.0

**Description / steps to reproduce**
1. Create a tier 1 fusion injector setup into a core
2. Wear Traveler's Vest from Tinkers Construct
3. Try to initiate crafting (e.g. the Wyvern injector recipe)
Regardless of power input or not, it won't even get to the "charging" text. Clicking the "Craft" button just does nothing.

Please, look into this to prevent anyone else the kind of absolute headache I just went through. Thanks!

![javaw_vEUPEUJK50](https://user-images.githubusercontent.com/102188421/164815931-c0b28595-7618-4d96-b1d1-78ce87a7cd27.gif)

**Comment by FoxMcloud5655** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/4838

**Comment by KnightMiner** [comment]
Any update on this? It makes no sense to me that armor would break the UI, if there is something broken in the armor code I need to know so I can fix it, or if this is an issue on your side that is useful information as well.

**Comment by brandon3055** [comment]
@KnightMiner Just did some digging. If a player is wearing your chestplate you block all `RightClickBlock` events.
https://github.com/SlimeKnights/TinkersConstruct/blob/1.18.2/src/main/java/slimeknights/tconstruct/tools/logic/InteractionHandler.java#L180
If a player does not have permission to right click one of my tiles then they do not have permission to send packets to that tile. 

The reason i do this is because without it, it would theoretically be possible to bypass grief prevention by sending a packet with a modified client. And such a packet could theoretically be used to detonate a DE reactor.

**Comment by KnightMiner** [comment]
There is a big difference between a canceled right click event and a player not having permission to perform an action, I disagree that is a fair assumption as that is the whole reason for the cancelation result. If you are going to base your behavior off the event being canceled, you should check the result to see if its a local "you have no permission" result, that is `FAIL`. Otherwise you will get false positives for anyone who adds an interaction during the event that happens to fire at your block. Likewise, firing the event can have side effects, how do you deal with the case where a modded item cancels the event when its in the main hand?

For a cleaner approach, why not just check if the player is in your container serverside? There is no way for them to be in the client side UI (without hacks) unless the serverside UI is open. If you enforce the UI only opens via the serverside right click block logic, you bypass the possibility of a hacked client opening it at the wrong time.

----

As far as claiming exclusive control over the event, that is why I only run my logic when you are wearing my chestplate and have an empty hand, and additionally I run it at low priority. Its unfortunately necessary to implement the logic in that way as forge does not fire enough events on right click for me to otherwise properly implement the relevant interaction hooks, no good way to change that without mixins (and if we are considering mixins to be a valid approach to the problem, one could simply mixin `Level#mayInteract` for their grief protection making that method sufficient for your needs)

**Comment by brandon3055** [comment]
> For a cleaner approach, why not just check if the player is in your container serverside?

You are correct here. I was talking to a friend about this issue last night and we came to the same conclusion. I just dont know how i missed this when i was implementing my system in the first place. I guess i was just so focused on replacing vanillas built it packet system with something better that i missed the one useful feature it has.

**Comment by FoxMcloud5655** [comment]
I'll note this for my mods if I ever need to do the same.  Good to know.

**Comment by brandon3055** [comment]
This is now fixed in a new release of BransonsCore
