### ISSUE TITLE
[1.16] Energy crystals are unbreakable

### ISSUE THREAD

**Issue by Travis9x** [Draconic-Inc/Draconic-Evolution#1672]
## Base information
* Minecraft version:  1.16.5
* Mod version:  3.0.27.462
* Minecraft Forge version:  36.2.35
* Mod Pack:  custom

### Description / steps to reproduce
Unsure when the bug was introduced, but it couldn't have been that long ago, since I recently upgraded several of the relay crystals in my energy network from Wyvern to Draconic.  But when I went back to finish upgrading the remaining Wyvern relay crystals, I found that ALL DE energy crystals (of any type, not just the relays) are completely unbreakable.  No tool can break/harvest them, and not "open hand" either.  I even tried hitting them with the Crystal Binder, having run out of other ideas.  
![UnbreakableCrystal](https://user-images.githubusercontent.com/8390575/178840974-53e1b523-16a7-4ea4-a6ee-e4bb99aac465.png)

**Comment by brandon3055** [comment]
It seems I forgot to set the required tool for the crystals. This means they can be harvested with any tool or no tool. However due to their hardness value, it takes a while to harvest them with vanilla tools, About 8 seconds with a diamond pickaxe. DE pickaxes can still harvest them at "normal" speeds which is probably why I never noticed the issue.

If they simply wont break no matter how long you mine them then its possible a mod in your pack is modifying the standard harvest logic and treating "no tool" as "indestructable"
