### ISSUE TITLE
[1.16] module problem in a minecraft server

### ISSUE THREAD

**Issue by Nonoahah506GX** [Draconic-Inc/Draconic-Evolution#1681]
when we recharge an item with modules inside, when we take back the item that is on the charger, the modules disappear, big bug

**Comment by Nonoahah506GX** [comment]
The server mods list : https://mega.nz/folder/8S8hCIZb#d60j4STFvlICfM2S5a58eg

**Comment by FoxMcloud5655** [comment]
It's customary to put the versions of Forge and whatever dependencies the mod you're reporting a bug for in your post, so please include those next time!

This is a very much known bug with how capabilities are handled.  Forge has an underlying bug that when you're in Creative mode, your modules will disappear when you pull up the Creative menu.  If this is happening in Survival mode and NOT in Creative mode, then whatever charger you're using doesn't handle capabilities properly and it's their fault.

**Comment by Nonoahah506GX** [comment]
ok, thank you and sorry for not having put all the characteristics for a bug report, so how can I solve this?

**Comment by Nonoahah506GX** [comment]
and this is the charger included in the mod that I use

**Comment by FoxMcloud5655** [comment]
It's alright!  If you're playing in Creative mode, then I urge you to play in Survival mode instead.  If you need items from the Creative menu, just use JEI instead to give yourself items.  You can do this by holding CTRL and clicking on the little wrench icon that JEI provides for changing settings.  It'll turn red and you can now pull items out of JEI instead of viewing the recipe for it.

If you're not playing in Creative mode, then use the Energy Transfuser from Draconic Evolution.  That's the block that allows you to charge, discharge, and transfer energy between items and your energy network.
