### ISSUE TITLE
[Feature Request] Suggesting renaming "Draconic" tier to "Awakened" tier

### ISSUE THREAD

**Issue by WISH-ETHEREAL** [Draconic-Inc/Draconic-Evolution#1691]
This feels like a very petty semantics change, but one I feel is worth mentioning regardless, as I remember it confusing me back in 1.12 and still throws me off when playing the mod in 1.16. Especially considering a tier is named "Draconium", I feel like a change like this frees up ambiguity and makes it more clear that the catalyst for the tier is Awakened Draconium.

**Comment by FoxMcloud5655** [comment]
Ultimately, this would be up to Brandon to accept.  However, I'm fairly certain that the names are set in place and won't change.  Draconium being the lowest tier makes sense since it's the only material required for the basic stuff.  Wyvern requires Nether Stars from Withers, and Draconic requires you to kill the dragon.  To me, it makes sense.

If Brandon wants to revisit this issue, he can open this back up, but I'll be sure to ask him directly about this at least once so he knows about it.
