### ISSUE TITLE
[1.12] bug Draconic Evolution rf not working

### ISSUE THREAD

**Issue by DKDragonWolf1619** [Draconic-Inc/Draconic-Evolution#1711]
* Minecraft version: 1.12.2 
* Mod version: Draconic Evolution 1.12.2-2.3.28.354 and Draconic Additions 1.12.2-1.17.0.45
* Minecraft Forge version: forge 14.23.5.2860
* Mod Pack: custom modpack  
bug

fusion crafting injection's can not get power nothing from Draconic Evolution or Draconic Additions gens or energy blocks are making rf power only making mrf or grf other mods installed do not produce rf or do not work with it can I have some help with this

![2023-02-07_17 56 02](https://user-images.githubusercontent.com/105707453/217173301-5d964e5c-44bc-4257-a7c7-56386daa588f.png)
![2023-02-07_17 56 08](https://user-images.githubusercontent.com/105707453/217173312-d4981772-5f2a-468d-b956-da91bec7f325.png)
![2023-02-07_17 56 15](https://user-images.githubusercontent.com/105707453/217173314-cf228257-93eb-4cf0-ac4b-0dcb679ba58c.png)
![2023-02-07_17 56 29](https://user-images.githubusercontent.com/105707453/217173315-009b454b-8548-40c4-8b40-61d86e46975c.png)
![2023-02-07_17 56 38](https://user-images.githubusercontent.com/105707453/217173321-8e28c451-ee7c-4857-9938-3cc8991d6fc5.png)
![2023-02-07_17 56 54](https://user-images.githubusercontent.com/105707453/217173326-d8bd0677-5f53-4d3a-be1e-b0f1f601d4ba.png)

**Comment by FoxMcloud5655** [comment]
Hold Shift and Right-Click the I/O Crystals with an empty hand to change their mode.  The ones attached to the Creative Energy Source need to "Input" from the block, and the ones attached to the Crafting Injectors need to "Output" to the block.

If you have further questions on this matter, please ask in the Discord rather than making a new issue here.
