### ISSUE TITLE
[1.16] Open GUI crash

### ISSUE THREAD

**Issue by XiaoDaiLuo** [Draconic-Inc/Draconic-Evolution#1715]
## Base information
* Minecraft version: 1.16.5
* Mod version:3.0.28
* Minecraft Forge version:36.2.39
* Mod Pack: Chroma Sky 2

### Crash report
https://paste.ubuntu.com/p/bkBnkyZnsX/

**Comment by FoxMcloud5655** [comment]
Without any context to this crash, all of this info is useless.

**Comment by Shotmas99ter** [comment]
I'm also having trouble opening or simply getting into the draconic mod part in the minecraft gui my game just crashes and closes and only has a log but apparently no mod is appearing to disrupt or crash the draconic mod the problems are his own apparently. The latest version of 1.16.5 the forge is the version 36.2.34 And the minecraft version is 1.16.5. Can anyone help me with this annoying error? 
I have the log file but do not know how to send because I am new here on github

**Comment by FoxMcloud5655** [comment]
Just drag and drop the file.

**Comment by FoxMcloud5655** [comment]
I revisited this issue, and it looks like you're on an old version of Draconic Evolution while being on a new version of CodeChickenLib.  Go update!
