### ISSUE TITLE
[1.16] unable to charge any item

### ISSUE THREAD

**Issue by DripOreo** [Draconic-Inc/Draconic-Evolution#1744]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.29.518
* Minecraft Forge version: 36.2.39

hello, currently i'm playing a modpack i made by myself (just added some popular mods), at the version 1.16.5, and there's a problem with charging any items (and i am using the right energy for that, i even tried FE, MFE, and more), for example, i can't charge my wyvern capacitor, not in the generator and not even in the energy transfuser, the same problem with the wyvern bow and my wyvern pickaxe, i already reinstalled the mod multiple times aswell as the other mods i need to play draconic evolution (codechickenlib, brandons core), can someone help me please? i played this mod at the version 1.12.2 and finished it, i really wanna play this mod again at the version 1.16.5, any help will be appreciated🙏.

**Comment by FoxMcloud5655** [comment]
Sounds like you are expecting everything to work the same as the 1.12.2 version.  This is a full rewrite of the mod.

The 1.16.5 version is completely unsupported right now; please use the 1.18.2 version.

As for your actual problem, please ask on the Discord server next time.  The issue is that you need to install Energy Modules into your equipment before using it.
