### ISSUE TITLE
[1.20.1] Rendering on Tools/Weapons in Left Handed Mode is Magical

### ISSUE THREAD

**Issue by Darkosto** [Draconic-Inc/Draconic-Evolution#1790]
## Base information
* Minecraft version: 1.20.1
* Mod version: June 13, 2024
* Minecraft Forge version: NeoForge 47.1.106
* Mod Pack: (if applicable): WIP SkyFactory 5

### Crash report
(If applicable)

### Description / steps to reproduce

Hey Brandon!

I hope that you're doing well and it's cool to see DE on a 1.20.1! Thank you very much for all your work. I ran into a small bug with the tools and weapons, when playing with left-handed mode on they float in the air: 

![image](https://github.com/Draconic-Inc/Draconic-Evolution/assets/10309699/f809488a-0910-4de4-86d3-6990982b7d9a)

I'm not sure if you were going for a new magical mod floaty sword. But if you were, it looks great! If not, then here's how to turn it on to test out when you're able. 

from within a world:
1. In-game options
4. Skin Customization
5. Main Hand: Left
6. Hold any of the DE tools and weapons

Looks like right hand works well on most everything else though! Thanks again for your time and have a terrific rest of your day,
Darkosto

**Comment by FoxMcloud5655** [comment]
It seems like the "off-hand" issue is actually a CCL issue.  Please post a new issue in CCL so it can get traction and get fixed!

**Comment by SkitzTGPG** [comment]
Isn't this mod dependent on CCL? This issue is still happening, and for left-handed folks like me it basically shuts me out of the majority of the mod. Which is a shame, as I love it - and wanted to include it in my next series.

I've added to the issue on the CCL page as well but figured getting the left hand to talk with the right (Since DE /depends/ on CCL to work~) Then maybe it can fixed.

Thank you again!
