### ISSUE TITLE
[1.20.1] Duping items in the reactor interface

### ISSUE THREAD

**Issue by MrLeonardosMi** [Draconic-Inc/Draconic-Evolution#1814]
## Base information
* Minecraft version: 1.20.1
* Mod version: (3.1.0-test-2.9999)
* Minecraft Forge version: 47.2.1
* Mod Pack: (if applicable)

### Description / steps to reproduce

If you go into the cooled reactor interface and try to pick up items(dragonium, chaos shards) via Ctrl, they won't pick up from the interface and will appear in inventory.

https://github.com/user-attachments/assets/f62d6137-ab32-46fa-a14f-c13a481d8800

**Comment by FoxMcloud5655** [comment]
Versions of Draconic Evolution that are compiled on your own are not supported.

**Comment by brandon3055** [comment]
Please check if this issue can be reproduced with the latest version from Curseforge. 

If the issue still occurs, then this may be related to an interaction with another mod, as I am unable to reproduce this issue myself.
I would need to know what mod is causing this issue in order to troubleshoot it.
