### ISSUE TITLE
[1.20.1] Bypass FTB claims (griefing)

### ISSUE THREAD

**Issue by funnycubeguy** [Draconic-Inc/Draconic-Evolution#1832]
The chaos dragon does not respect FTB chunks claims, and completely bypasses them allowing servers to be completely griefed. It is one of the worst grief methods I have seen by far especially when using other mods to capture and teleport the dragon around. Please add some checks for FTB chunks, thanks.

EDIT: Another note maybe consider a way to respawn the dragon on  islands for servers... :)

**Comment by FoxMcloud5655** [comment]
First, by griefing, you mean killing players, right?  Not destroying blocks?  Because it doesn't do that.

Second, there already is a respawn command.  `/respawn_draconic_guardian`, if I'm not mistaken.  Just `/setblock` on the original crystal's position to creat a new crystal, then summon a new guardian with the command.

**Comment by FoxMcloud5655** [comment]
If you ARE talking about killing players, then imagine if someone claimed the entire Chaos Island and completely bypassed the fight by becoming invincible to attacks from the guardian.  That's a big fat nope.
